name: 'Angular Build and Deploy to AWS Elastic Beanstalk'

on:
  push:
    branches:
    - dev

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ vars.AWS_REGION }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Node.Js 16.x, Angular CLI and execute build process
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - run: |
        npm install -g @angular/cli@16.2.11
        npm install
        ng build

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: |
          dist
          !dist/**/*.md

  deploy:
    runs-on: ubuntu-latest
    environment: development
    needs: build
    steps:
    - name: Download Build Artifact
      uses: actions/download-artifact@v3
      with:
        name: build
    
    #- name: Checkout
    #  uses: actions/checkout@v4
    
    #- name: Configure AWS Credentials
    #  uses: aws-actions/configure-aws-credentials@v3
    #  with:
    #    aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
    #    aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
    #    aws-region: ${{ env.AWS_REGION }}
    
    #- name: Troubleshoot
    #  run: | 
    #    pwd
    #    cd demo-aws
    #    pwd
    #    ls

    - name: Deploy Build Artifact to AWS Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v21   
      with:
        aws_access_key: ${{ env.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        application_name: demo-aws-app-dev
        environment_name: demo-aws-app-env-dev
        version_label: ${{ github.run_number }}
        region: ${{ env.AWS_REGION }}
        use_existing_version_if_available: true
        deployment_package: demo-aws
