# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches:
    - dev
  pull_request:
    branches:
    - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Node.Js 16.x, Angular CLI and execute build process
      uses: actions/setup-node@v3
      with:
        node-version: "16.x"
    - run: |
        npm install -g @angular/cli
        ng build

    - name: ZIP Files
      run: zip -r build.zip * .[^.]* -x "**node_modules**"

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v16
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: demo-aws-app-dev
        environment_name: demo-aws-app-env-dev
        region: ${{ vars.AWS_REGION }}
        deployment_package: build.zip
    
